apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingapp
  template:
    metadata:
      labels:
        app: bookingapp
    spec:
      containers:
      - name: bookingapp
        image: lala27/conf-booking:latest
        ports:
        - containerPort: 8080
